print("")
my_name = input("What's your name? ")
neighbor_name = input("What's your neighbor's name? ")
my_months_coding = input("How many months have you been coding? ")
neighbor_months_coding = input("How many months has your neighbor been coding? ")
print("")
print("Let me think about that...")
print("")
import time
time.sleep(1)
print("...")
print("")
print(str(my_name) + " has been coding for " + str(my_months_coding) + " months. ")
print(str(neighbor_name) + " has been coding for " + str(neighbor_months_coding) + " months. ")
print("")